// =============================================
// YourUtopia — Country Starting Data
// =============================================
import { CountryTemplate } from "./types";

export const COUNTRIES: (CountryTemplate & { code: string })[] = [
  {
    name: "Kuzey Kore",
    flag: "🇰🇵",
    code: "kp",
    population: 26.0,
    budget: 1000,
    military: 90,
    happiness: 10,
    health: 25,
    environment: 40,
    education: 45,
    stability: 85,
    foreignRelations: 5,
    energy: 40,
    food: 20,
    materials: 80,
    regime: "Otokrasi",
    difficulty: "Çok Zor",
    description: "Dünyaya tamamen kapalı. Ambargo nedeniyle dış ticaret geliri yoktur ve halk kronik açlık çeker. İstikrar %80'in altına düşerse korku duvarı yıkılır ve kaos başlar. Tam bir cehennem.",
  },
  {
    name: "Amerika Birleşik Devletleri",
    flag: "🇺🇸",
    code: "us",
    population: 335.0,
    budget: 15000,
    military: 90,
    happiness: 50,
    health: 45,
    environment: 35,
    education: 70,
    stability: 65,
    foreignRelations: 65,
    energy: 90,
    food: 100,
    materials: 100,
    regime: "Demokrasi",
    difficulty: "Orta",
    description:
      "Dünyanın en büyük ekonomisi ve askeri gücü. Aşırı kutuplaşma istikrarı tehdit ediyor, sağlık sistemi pahalı.",
  },
  {
    name: "İsveç",
    flag: "🇸🇪",
    code: "se",
    population: 10.5,
    budget: 5000,
    military: 25,
    happiness: 85,
    health: 90,
    environment: 95,
    education: 85,
    stability: 85,
    foreignRelations: 80,
    energy: 60,
    food: 60,
    materials: 50,
    regime: "Demokrasi",
    difficulty: "Kolay",
    description:
      "Kuzeyin refah devleti. Mutluluk ve çevre mükemmel seviyede ancak düşük askeri güç olası savaşlarda ülkeyi savunmasız bırakabilir.",
  },
  {
    name: "Türkiye",
    flag: "🇹🇷",
    code: "tr",
    population: 85.0,
    budget: 4000,
    military: 75,
    happiness: 35,
    health: 50,
    environment: 35,
    education: 45,
    stability: 40,
    foreignRelations: 35,
    energy: 40,
    food: 70,
    materials: 60,
    regime: "Demokrasi",
    difficulty: "Zor",
    description:
      "Bölgesel güç. Güçlü bir askeri yapıya sahip ancak kırılgan ekonomi ve toplumsal kutuplaşma yönetimi son derece zorlaştırıyor.",
  },
  {
    name: "Brezilya",
    flag: "🇧🇷",
    code: "br",
    population: 215.0,
    budget: 6000,
    military: 35,
    happiness: 45,
    health: 40,
    environment: 80,
    education: 40,
    stability: 45,
    foreignRelations: 55,
    energy: 80,
    food: 90,
    materials: 70,
    regime: "Demokrasi",
    difficulty: "Zor",
    description:
      "Zengin kaynaklar, derin eşitsizlik. Amazon yangınları çevre puanını tüketirken, düşük eğitim ülkenin potansiyelini kilitliyor.",
  },
  {
    name: "Japonya",
    flag: "🇯🇵",
    code: "jp",
    population: 125.0,
    budget: 14000,
    military: 45,
    happiness: 60,
    health: 85,
    environment: 65,
    education: 90,
    stability: 80,
    foreignRelations: 60,
    energy: 30,
    food: 40,
    materials: 90,
    regime: "Demokrasi",
    difficulty: "Orta",
    description:
      "Teknoloji devi. Mükemmel eğitim ve sağlık, ancak yaşlanan nüfus ve aşırı çalışma kültürü büyümeyi sınırlandırıyor.",
  },
  {
    name: "Nijerya",
    flag: "🇳🇬",
    code: "ng",
    population: 220.0,
    budget: 2000,
    military: 30,
    happiness: 25,
    health: 20,
    environment: 25,
    education: 20,
    stability: 20,
    foreignRelations: 20,
    energy: 80,
    food: 50,
    materials: 50,
    regime: "Demokrasi",
    difficulty: "Çok Zor",
    description:
      "Afrika'nın kalabalık devi. Dev potansiyel ama diplerde gezen sağlık, eğitim ve istikrar. Sadece uzman oyuncular için hayatta kalma mücadelesi.",
  },
  {
    name: "Almanya",
    flag: "🇩🇪",
    code: "de",
    population: 84.0,
    budget: 12000,
    military: 40,
    happiness: 65,
    health: 80,
    environment: 75,
    education: 85,
    stability: 75,
    foreignRelations: 80,
    energy: 50,
    food: 60,
    materials: 80,
    regime: "Demokrasi",
    difficulty: "Kolay",
    description:
      "Avrupa'nın motoru. Sanayi ve diplomasi çok güçlü. Enerji geçişi ve dış politikayı dengelemek anahtar kural.",
  },
  {
    name: "Rusya",
    flag: "🇷🇺",
    code: "ru",
    population: 144.0,
    budget: 9000,
    military: 85,
    happiness: 30,
    health: 50,
    environment: 30,
    education: 60,
    stability: 65,
    foreignRelations: 15,
    energy: 100,
    food: 80,
    materials: 90,
    regime: "Otokrasi",
    difficulty: "Zor",
    description:
      "Küresel tecrit altındaki süper güç. Devasa askeri kapasite ve kaynaklar, dibe vurmuş diplomasi ve halk mutluluğu ile birleşiyor.",
  },
  {
    name: "Çin",
    flag: "🇨🇳",
    code: "cn",
    population: 1412.0,
    budget: 25000,
    military: 85,
    happiness: 40,
    health: 60,
    environment: 20,
    education: 85,
    stability: 90,
    foreignRelations: 45,
    energy: 70,
    food: 90,
    materials: 100,
    regime: "Otokrasi",
    difficulty: "Orta",
    description: "Sarsılmaz otorite. İstikrar, bütçe ve üretim kapasitesi devasa, ancak çevre kirliliği sınırları zorluyor.",
  },
  {
    name: "Hindistan",
    flag: "🇮🇳",
    code: "in",
    population: 1428.0,
    budget: 12000,
    military: 70,
    happiness: 45,
    health: 35,
    environment: 30,
    education: 55,
    stability: 50,
    foreignRelations: 60,
    energy: 60,
    food: 80,
    materials: 70,
    regime: "Demokrasi",
    difficulty: "Zor",
    description: "Nüfus bombası. Muazzam bir büyüme potansiyeli var ancak temiz su, sağlık ve altyapı krizleri baş ağrıtıcı seviyede.",
  },
  {
    name: "İngiltere",
    flag: "🇬🇧",
    code: "gb",
    population: 68.0,
    budget: 12000,
    military: 60,
    happiness: 60,
    health: 75,
    environment: 70,
    education: 80,
    stability: 65,
    foreignRelations: 70,
    energy: 40,
    food: 50,
    materials: 60,
    regime: "Demokrasi",
    difficulty: "Orta",
    description: "Küresel nüfuzunu korumaya çalışan ada ülkesi. Sağlık sistemi zorlanıyor, ekonomi ise geçmişteki şaşalı günlerini arıyor.",
  },
  {
    name: "Güney Kore",
    flag: "🇰🇷",
    code: "kr",
    population: 51.0,
    budget: 11000,
    military: 70,
    happiness: 40,
    health: 90,
    environment: 60,
    education: 95,
    stability: 75,
    foreignRelations: 70,
    energy: 30,
    food: 40,
    materials: 90,
    regime: "Demokrasi",
    difficulty: "Orta",
    description: "Aşırı rekabetçi teknoloji merkezi. Eğitim ve sağlık zirvede fakat acımasız sistem halkın mutluluğunu kemiriyor.",
  },
  {
    name: "Suudi Arabistan",
    flag: "🇸🇦",
    code: "sa",
    population: 36.0,
    budget: 15000,
    military: 70,
    happiness: 55,
    health: 60,
    environment: 20,
    education: 45,
    stability: 75,
    foreignRelations: 55,
    energy: 100,
    food: 20,
    materials: 40,
    regime: "Otokrasi",
    difficulty: "Orta",
    description: "Petrodolar imparatorluğu. Sınırsız bütçeye rağmen doğa can çekişiyor, ekonomi tamamen tek bir kaynağa bağlı.",
  },
];
