// =============================================
// YourUtopia — Country Starting Data
// =============================================
import { CountryTemplate } from "./types";

export const COUNTRIES: CountryTemplate[] = [
  {
    name: "Amerika Birleşik Devletleri",
    flag: "🇺🇸",
    budget: 15000,
    military: 90,
    happiness: 50,
    health: 60,
    environment: 35,
    education: 60,
    stability: 55,
    foreignRelations: 75,
    difficulty: "Orta",
    description:
      "Dünyanın en büyük ekonomisi ve askeri gücü. Aşırı kutuplaşma istikrarı tehdit ediyor, sağlık sistemi pahalı.",
  },
  {
    name: "İsveç",
    flag: "🇸🇪",
    budget: 10000,
    military: 25,
    happiness: 85,
    health: 90,
    environment: 90,
    education: 90,
    stability: 85,
    foreignRelations: 80,
    difficulty: "Kolay",
    description:
      "Kuzeyin refah devleti. Mutluluk ve çevre mükemmel seviyede ancak düşük askeri güç olası savaşlarda ülkeyi savunmasız bırakabilir.",
  },
  {
    name: "Türkiye",
    flag: "🇹🇷",
    budget: 8000,
    military: 75,
    happiness: 35,
    health: 50,
    environment: 40,
    education: 50,
    stability: 40,
    foreignRelations: 50,
    difficulty: "Zor",
    description:
      "Bölgesel güç. Güçlü bir askeri yapıya sahip ancak kırılgan ekonomi ve toplumsal kutuplaşma yönetimi son derece zorlaştırıyor.",
  },
  {
    name: "Brezilya",
    flag: "🇧🇷",
    budget: 8000,
    military: 35,
    happiness: 45,
    health: 40,
    environment: 50,
    education: 35,
    stability: 40,
    foreignRelations: 45,
    difficulty: "Zor",
    description:
      "Zengin kaynaklar, derin eşitsizlik. Amazon yangınları çevre puanını tüketirken, düşük eğitim ülkenin potansiyelini kilitliyor.",
  },
  {
    name: "Japonya",
    flag: "🇯🇵",
    budget: 14000,
    military: 45,
    happiness: 60,
    health: 90,
    environment: 55,
    education: 90,
    stability: 80,
    foreignRelations: 70,
    difficulty: "Orta",
    description:
      "Teknoloji devi. Mükemmel eğitim ve sağlık, ancak yaşlanan nüfus ve aşırı çalışma kültürü büyümeyi sınırlandırıyor.",
  },
  {
    name: "Nijerya",
    flag: "🇳🇬",
    budget: 6000,
    military: 30,
    happiness: 25,
    health: 20,
    environment: 40,
    education: 20,
    stability: 25,
    foreignRelations: 35,
    difficulty: "Çok Zor",
    description:
      "Afrika'nın kalabalık devi. Dev potansiyel ama diplerde gezen sağlık, eğitim ve istikrar. Sadece uzman oyuncular için hayatta kalma mücadelesi.",
  },
  {
    name: "Almanya",
    flag: "🇩🇪",
    budget: 13000,
    military: 50,
    happiness: 70,
    health: 80,
    environment: 70,
    education: 85,
    stability: 75,
    foreignRelations: 85,
    difficulty: "Kolay",
    description:
      "Avrupa'nın motoru. Sanayi ve diplomasi çok güçlü. Enerji geçişi ve dış politikayı dengelemek anahtar kural.",
  },
  {
    name: "Rusya",
    flag: "🇷🇺",
    budget: 9000,
    military: 85,
    happiness: 30,
    health: 50,
    environment: 30,
    education: 60,
    stability: 65,
    foreignRelations: 15,
    difficulty: "Zor",
    description:
      "Küresel tecrit altındaki süper güç. Devasa askeri kapasite ve kaynaklar, dibe vurmuş diplomasi ve halk mutluluğu ile birleşiyor.",
  },
  {
    name: "Çin",
    flag: "🇨🇳",
    budget: 16000,
    military: 85,
    happiness: 40,
    health: 60,
    environment: 20,
    education: 85,
    stability: 90,
    foreignRelations: 45,
    difficulty: "Orta",
    description: "Sarsılmaz otorite. İstikrar, bütçe ve üretim kapasitesi devasa, ancak çevre kirliliği sınırları zorluyor.",
  },
  {
    name: "Hindistan",
    flag: "🇮🇳",
    budget: 9000,
    military: 70,
    happiness: 45,
    health: 35,
    environment: 30,
    education: 55,
    stability: 50,
    foreignRelations: 60,
    difficulty: "Zor",
    description: "Nüfus bombası. Muazzam bir büyüme potansiyeli var ancak temiz su, sağlık ve altyapı krizleri baş ağrıtıcı seviyede.",
  },
  {
    name: "İngiltere",
    flag: "🇬🇧",
    budget: 12000,
    military: 60,
    happiness: 60,
    health: 75,
    environment: 70,
    education: 80,
    stability: 65,
    foreignRelations: 70,
    difficulty: "Orta",
    description: "Küresel nüfuzunu korumaya çalışan ada ülkesi. Sağlık sistemi zorlanıyor, ekonomi ise geçmişteki şaşalı günlerini arıyor.",
  },
  {
    name: "Güney Kore",
    flag: "🇰🇷",
    budget: 11000,
    military: 70,
    happiness: 40,
    health: 90,
    environment: 60,
    education: 95,
    stability: 75,
    foreignRelations: 70,
    difficulty: "Orta",
    description: "Aşırı rekabetçi teknoloji merkezi. Eğitim ve sağlık zirvede fakat acımasız sistem halkın mutluluğunu kemiriyor.",
  },
  {
    name: "Suudi Arabistan",
    flag: "🇸🇦",
    budget: 15000,
    military: 70,
    happiness: 55,
    health: 60,
    environment: 20,
    education: 45,
    stability: 75,
    foreignRelations: 55,
    difficulty: "Orta",
    description: "Petrodolar imparatorluğu. Sınırsız bütçeye rağmen doğa can çekişiyor, ekonomi tamamen tek bir kaynağa bağlı.",
  },
  {
    name: "Kuzey Kore",
    flag: "🇰🇵",
    budget: 2000,
    military: 80,
    happiness: 10,
    health: 20,
    environment: 30,
    education: 40,
    stability: 95,
    foreignRelations: 5,
    difficulty: "Çok Zor",
    description: "Dünyadan tamamen izole, korkuyla yönetilen nükleer bir kale. Halk açlık sınırında, diplomasi sıfır, tek güçlü yanınız askeriye ve sarsılmaz otoriteniz.",
  },
];
