// =============================================
// YourUtopia — Country Starting Data
// =============================================
import { CountryTemplate } from "./types";

export const COUNTRIES: CountryTemplate[] = [
  {
    name: "Amerika Birleşik Devletleri",
    flag: "🇺🇸",
    budget: 8000,
    military: 85,
    happiness: 55,
    health: 60,
    environment: 35,
    education: 70,
    stability: 60,
    foreignRelations: 65,
    difficulty: "Orta",
    description:
      "Dünyanın en büyük ekonomisi ve askeri gücü. Yüksek savunma harcamaları bütçeyi zorlayabilir, çevre politikaları zayıf.",
  },
  {
    name: "İsveç",
    flag: "🇸🇪",
    budget: 5000,
    military: 30,
    happiness: 85,
    health: 90,
    environment: 85,
    education: 90,
    stability: 85,
    foreignRelations: 80,
    difficulty: "Kolay",
    description:
      "Refah devleti modeli. Yüksek eğitim ve sosyal göstergeler ama düşük askeri güç ve sınırlı bütçe.",
  },
  {
    name: "Türkiye",
    flag: "🇹🇷",
    budget: 4000,
    military: 65,
    happiness: 45,
    health: 50,
    environment: 40,
    education: 55,
    stability: 45,
    foreignRelations: 50,
    difficulty: "Zor",
    description:
      "Köprü ülke — Avrupa ile Asya arasında stratejik konumda. Dengeli ama kırılgan bir yapı, her cephede dikkatli yönetim gerektirir.",
  },
  {
    name: "Brezilya",
    flag: "🇧🇷",
    budget: 3500,
    military: 40,
    happiness: 50,
    health: 40,
    environment: 60,
    education: 35,
    stability: 40,
    foreignRelations: 45,
    difficulty: "Zor",
    description:
      "Zengin doğal kaynaklar ama derin eşitsizlik. Amazon ormanları çevre puanını yükseltiyor, ancak eğitim ve sağlık zayıf.",
  },
  {
    name: "Japonya",
    flag: "🇯🇵",
    budget: 7000,
    military: 45,
    happiness: 60,
    health: 85,
    environment: 55,
    education: 90,
    stability: 80,
    foreignRelations: 70,
    difficulty: "Orta",
    description:
      "Teknoloji devi. Mükemmel eğitim ve sağlık altyapısı, ama yaşlanan nüfus ve sınırlı askeri güç zorluk yaratabilir.",
  },
  {
    name: "Nijerya",
    flag: "🇳🇬",
    budget: 2000,
    military: 30,
    happiness: 35,
    health: 25,
    environment: 45,
    education: 20,
    stability: 30,
    foreignRelations: 35,
    difficulty: "Çok Zor",
    description:
      "Afrika'nın en kalabalık ülkesi. Düşük başlangıç statları ile her tur hayatta kalma mücadelesi. Uzman oyuncular için!",
  },
  {
    name: "Almanya",
    flag: "🇩🇪",
    budget: 6500,
    military: 50,
    happiness: 70,
    health: 80,
    environment: 70,
    education: 85,
    stability: 75,
    foreignRelations: 85,
    difficulty: "Kolay",
    description:
      "Avrupa'nın motoru. Güçlü ekonomi, yüksek eğitim ve diplomasi. Dengeyi korumak nispeten kolay ama rehavet tehlikeli!",
  },
  {
    name: "Rusya",
    flag: "🇷🇺",
    budget: 5500,
    military: 80,
    happiness: 35,
    health: 50,
    environment: 30,
    education: 60,
    stability: 55,
    foreignRelations: 25,
    difficulty: "Zor",
    description:
      "Askeri süper güç ama düşük mutluluk ve diplomatik izolasyon. Çevre sorunları sağlığı tehdit ediyor. Dengeyi bulmak zor.",
  },
  {
    name: "Çin",
    flag: "🇨🇳",
    budget: 9000,
    military: 90,
    happiness: 45,
    health: 65,
    environment: 30,
    education: 85,
    stability: 85,
    foreignRelations: 55,
    difficulty: "Orta",
    description: "Devasa bütçe ve sanayi gücü. Çevre kirliliği hat safhada, otoriter yapı istikrarı yüksek tutuyor.",
  },
  {
    name: "Hindistan",
    flag: "🇮🇳",
    budget: 4500,
    military: 75,
    happiness: 55,
    health: 40,
    environment: 35,
    education: 65,
    stability: 50,
    foreignRelations: 60,
    difficulty: "Zor",
    description: "Büyüyen nüfus ve potansiyel. Sağlık ve çevre alanında büyük yatırımlara ihtiyaç var.",
  },
  {
    name: "İngiltere",
    flag: "🇬🇧",
    budget: 6000,
    military: 60,
    happiness: 65,
    health: 85,
    environment: 75,
    education: 85,
    stability: 70,
    foreignRelations: 75,
    difficulty: "Kolay",
    description: "Tarihi güç ve diplomasi merkezi. İstikrarlı bir ekonomi ancak küresel etkisini korumakta zorlanıyor.",
  },
  {
    name: "Güney Kore",
    flag: "🇰🇷",
    budget: 5500,
    military: 65,
    happiness: 45,
    health: 90,
    environment: 70,
    education: 95,
    stability: 75,
    foreignRelations: 70,
    difficulty: "Orta",
    description: "Teknoloji ve eğitimde zirve noktası. Aşırı rekabetçi ortam mutluluğu düşürüyor.",
  },
  {
    name: "Suudi Arabistan",
    flag: "🇸🇦",
    budget: 8500,
    military: 70,
    happiness: 60,
    health: 65,
    environment: 25,
    education: 50,
    stability: 70,
    foreignRelations: 60,
    difficulty: "Orta",
    description: "Petrol zengini. Bütçe güçlü ancak eğitim ve çevre sorunları uzun vadede tehlike yaratabilir.",
  },
];
